import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/home.module.scss";
import { useRouter } from "next/router";
import { useState } from "react";
import Image from "next/image";
import MenuActions from "../components/MenuActions";
import Link from "next/link";

const Home: NextPage = () => {
	const [loading, setLoading] = useState(false);
	const router = useRouter();

	const goTo = (link: string) => {
		router.push(link);
		setLoading(true);
	};

	return (
		<div>
			<Head>
				<title>Menu - TERRAÇO DA ALTA</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.container}>
				{loading && <div className={styles.loader}></div>}
				<MenuActions id="actions" />
				<div className={styles.cardContainer} onClick={() => goTo("/pt")}>
					<Image
						src="/assets/img/button01.svg"
						className="card-img-top"
						alt="Português"
						width={320}
						height={280}
					/>
				</div>
				<div className={styles.cardContainer} onClick={() => goTo("/en")}>
					<Image
						src="/assets/img/button02.svg"
						className="card-img-top"
						alt="English"
						width={320}
						height={280}
					/>
				</div>
				<div style={{ cursor: "pointer" }}>
					<Link href="https://www.livroreclamacoes.pt/inicio" target="_blank">
						<Image
							src="/assets/img/livro_reclamacoes.png"
							alt="livro de reclamações"
							width={90}
							height={45}
						/>
					</Link>
				</div>
			</main>
		</div>
	);
};

export default Home;
